services:
  postgre:
    image: postgres:13.13
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
  kubenews:
    image: wbgm/kube-news:latest
    depends_on:
      - postgre
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg123
      DB_HOST: postgre
networks:
  kubenews_net:
    driver: bridge
